### ISSUE TITLE
RealtimeClient not working while RLS is enabled, but SupabaseClient can access data while RLS is enabled.

### ISSUE THREAD

**Issue by sazidbs23** [supabase/realtime-swift#19]
# Bug report

## Describe the bug

After connecting to RealtimeClient and subscribing to channel everything works fine while RLS is disabled, i.e. getting any event(insert, delete, update) from corresponding table. 

But whenever RLS is enabled i'm not getting any event on channel subscription for desired database table. FYI I can access data(read, insert, delete, update) from that desired table after RLS is enabled. Only problem is didn't receiving any event in RealtimeClient subscription while RLS is enabled.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Make a channel subscription:
```
        let userChanges = realtimeClient.channel(.table("table-name", schema: "public"))

        userChanges.on(.insert) { message in
            print("### insert message ###")
        }
        userChanges.on(.delete) { message in
            print("### delete message ###")
        }
        userChanges.on(.update) { message in
            print("### update message ###")
        }

        userChanges.subscribe()
```
2. Disable RLS in table `table-name`.
3. Get the result properly.
4. Enable RLS in table `table-name`.
5. You will not get any event or update from the channel.
6. But you can access data from `table-name` with corresponding RLS is enabled.

## Expected behavior

As I can access data from desired table with RLS enabled it is expected to get RealtimeClient update also while RLS is enabled.

## System information

- OS: [iOS 16.2]
- Version of supabase-realtime: [0.0.2]
- Version of supabase-swift: [0.2.1]

**Comment by vilimas** [comment]
https://github.com/supabase-community/realtime-swift/issues/15#issuecomment-1489609071

This is the answer if somebody is having the same problem. I think docs should mention this use case.
