### ISSUE TITLE
Issue With Channel + Schema 

### ISSUE THREAD

**Issue by lmick002** [supabase/realtime-swift#3]
I love the project 

Im running into a when setting up a channel listener on a table with public schema. 

Currently, I can only receive data from my supabase DB if I'm using `realtime:*`, but whenever set a specific table with the schema set public:

`channel(.table("Media", schema: "public"))`
 
the listener returns no data and after the socket opens, it emits a Close Event shortly after.  I made sure all of my tables were public and also replicated as per the requirements for real-time setup. 

<img width="578" alt="Screen Shot 2022-01-14 at 2 24 17 PM" src="https://user-images.githubusercontent.com/11696955/149573637-85d347cd-9588-4632-8d6a-d2a5d4915b11.png">

Thanks you for the help!

**Comment by lmick002** [comment]
Any thoughts @satishbabariya ?

**Comment by barisuyar** [comment]
Hi, i am facing with that issue too. If i create a channel with .all option there is no problem. But the other options are failed.
