### ISSUE TITLE
StarScream Dependency prevents importing into Swift Playgrounds 4

### ISSUE THREAD

**Issue by YeomansIII** [supabase/realtime-swift#8]
This is definitely an edge case, but something I think that is important.

The realtime-swift package cannot be imported into Swift Playgrounds 4 because of the dependency on StarScream. realtime-swift can already run with StarScream removed since an implementation of the Transport protocol using standard iOS libraries exists. Please see my fork for a working repo that can import into Swift Playgrounds 4: https://github.com/YeomansIII/realtime-swift

Through my research, these Supabase Swift libraries (postgrest-swift, storage-swift, gotrue-swift) are some of the only 100% Swift packages that can actually be imported into Swift Playgrounds 4, which allows developers to create iOS apps directly on iPadOS without a Mac computer. This was important for me, because I was looking for a no-code backend like Firebase to use for my iOS app I am developing in Swift Playgrounds 4. Firebase and numerous other similar platforms were not able to be imported into Swift Playgrounds 4 because the packages contain Objective-C or other incompatible code/settings.

While I know that removing the StarScream dependency allows importing into Swift Playgrounds 4, I do not know if this is an actual solution or what the potential solution might be to get the main realtime-swift repo working with Swift Playgrounds.

So I would like to open up that discussion here.

**Comment by grdsdev** [comment]
I'm ok in dropping support for older iOS versions in favor of having a dependency free package, can you open a PR with your changes?

I'll be glad reviewing it.

**Comment by grdsdev** [comment]
Fixed on 0.0.2
