### ISSUE TITLE
Starscream dependency on zlib

### ISSUE THREAD

**Issue by johndpope** [supabase/realtime-swift#9]
https://github.com/daltoniam/Starscream/pull/844

this prevents xcframeworks being spat out
https://github.com/supabase-community/supabase-swift/issues/38

**Comment by grdsdev** [comment]
Hi @johndpope 

I decided to align the minimum supported platform of this library to the `supabase-swift`, that makes it possible to remove the `starscream` dependency, as you can check on https://github.com/supabase-community/realtime-swift/pull/11

Does that solve your problem?
